# Generated by Django 5.2.4 on 2025-08-04 15:44

import django.core.validators
import django.db.models.deletion
import uuid
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('track_id', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detected Object',
                'verbose_name_plural': 'Detected Objects',
                'db_table': 'detected_objects',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=videos.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('resolution_width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_height', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('analysis_types', models.JSONField(default=list)),
                ('custom_rules', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('violation', 'Violation'), ('critical', 'Critical')], default='info', max_length=20)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('detected_by', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('is_violation', models.BooleanField(default=False)),
                ('guideline_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_objects', models.ManyToManyField(blank=True, to='videos.detectedobject')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='videos.video')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.PositiveIntegerField()),
                ('timestamp', models.FloatField()),
                ('image', models.ImageField(upload_to='frames/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('has_objects', models.BooleanField(default=False)),
                ('has_events', models.BooleanField(default=False)),
                ('is_keyframe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Frame',
                'verbose_name_plural': 'Video Frames',
                'db_table': 'video_frames',
                'ordering': ['timestamp'],
                'unique_together': {('video', 'frame_number')},
            },
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='videos.videoframe'),
        ),
    ]
