# Generated by Django 5.2.4 on 2025-08-04 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('analysis_types', models.JSONField(default=list)),
                ('custom_rules', models.JSONField(default=dict)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('total_events_detected', models.PositiveIntegerField(default=0)),
                ('total_violations_detected', models.PositiveIntegerField(default=0)),
                ('total_objects_detected', models.PositiveIntegerField(default=0)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'db_table': 'analysis_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Recognition'), ('anomaly', 'Anomaly Detection'), ('trend', 'Trend Analysis'), ('recommendation', 'Recommendation'), ('alert', 'Alert'), ('prediction', 'Prediction')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('evidence_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('is_actionable', models.BooleanField(default=False)),
                ('recommended_actions', models.JSONField(default=list)),
                ('relevant_timeframe_start', models.FloatField(blank=True, null=True)),
                ('relevant_timeframe_end', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'db_table': 'insights',
                'ordering': ['-priority', '-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_processing_time', models.FloatField()),
                ('total_videos_processed', models.PositiveIntegerField()),
                ('total_events_detected', models.PositiveIntegerField()),
                ('total_insights_generated', models.PositiveIntegerField()),
                ('model_accuracy_scores', models.JSONField(default=dict)),
                ('model_usage_statistics', models.JSONField(default=dict)),
                ('cpu_usage_average', models.FloatField(blank=True, null=True)),
                ('memory_usage_average', models.FloatField(blank=True, null=True)),
                ('storage_usage', models.BigIntegerField(blank=True, null=True)),
                ('error_rate', models.FloatField(default=0.0)),
                ('common_errors', models.JSONField(default=dict)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_videos_uploaded', models.PositiveIntegerField(default=0)),
                ('total_analysis_time', models.DurationField()),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('most_used_analysis_types', models.JSONField(default=list)),
                ('favorite_video_categories', models.JSONField(default=list)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('most_active_time_of_day', models.TimeField(blank=True, null=True)),
                ('insights_acknowledged', models.PositiveIntegerField(default=0)),
                ('feedback_provided', models.PositiveIntegerField(default=0)),
                ('first_activity', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='VideoSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('overview', 'Overview'), ('events', 'Events Summary'), ('violations', 'Violations Summary'), ('objects', 'Objects Summary'), ('timeline', 'Timeline Summary')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('key_points', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=100)),
                ('generation_time', models.FloatField()),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Summary',
                'verbose_name_plural': 'Video Summaries',
                'db_table': 'video_summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
