# Generated by Django 5.2.4 on 2025-08-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='videos.video'),
        ),
        migrations.AddField(
            model_name='insight',
            name='analysis_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.analysissession'),
        ),
        migrations.AddField(
            model_name='insight',
            name='supporting_events',
            field=models.ManyToManyField(blank=True, to='videos.event'),
        ),
        migrations.AddField(
            model_name='insight',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='videos.video'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videosummary',
            name='analysis_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='analytics.analysissession'),
        ),
        migrations.AddField(
            model_name='videosummary',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='videosummary',
            unique_together={('video', 'summary_type')},
        ),
    ]
