# Generated by Django 5.2.4 on 2025-08-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='videos.video'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='current_video_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='mentioned_events',
            field=models.ManyToManyField(blank=True, to='videos.event'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='referenced_events',
            field=models.ManyToManyField(blank=True, to='videos.event'),
        ),
        migrations.AddField(
            model_name='message',
            name='referenced_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video'),
        ),
    ]
